In [2]:
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[35, 6420, 7917, 3774],
 [35, 6420, 7917, 903],
 [35, 9711, 7917, 6820],
 [4480, 8480, 7039, 7912, 5365],
 [4480, 8480, 7039, 7912, 6324],
 [4222, 35, 8102, 7917, 6736],
 [8318, 7510, 8373, 7912]]

In [17]:

## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [18]:
import numpy as np

In [19]:
## we have to make all sentences of same length
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0   35 6420 7917 3774]
 [   0    0    0    0   35 6420 7917  903]
 [   0    0    0    0   35 9711 7917 6820]
 [   0    0    0 4480 8480 7039 7912 5365]
 [   0    0    0 4480 8480 7039 7912 6324]
 [   0    0    0 4222   35 8102 7917 6736]
 [   0    0    0    0 8318 7510 8373 7912]]


In [20]:
## feature representation
dim=10         # here we are using 10 dimensions instead of 300

In [24]:
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=10))
model.build(input_shape=(None, 8))  # 8 = sentence length
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
from tensorflow.keras import Input

model = Sequential([
    Input(shape=(8,)),
    Embedding(input_dim=10000, output_dim=10)
])
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=10))
model(np.array(embedded_docs))  # Call the model once
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step


array([[[-0.02572331, -0.00419756, -0.01576333, -0.00369692,
         -0.04649016, -0.02225201, -0.04041226, -0.02301608,
         -0.04000423,  0.01110721],
        [-0.02572331, -0.00419756, -0.01576333, -0.00369692,
         -0.04649016, -0.02225201, -0.04041226, -0.02301608,
         -0.04000423,  0.01110721],
        [-0.02572331, -0.00419756, -0.01576333, -0.00369692,
         -0.04649016, -0.02225201, -0.04041226, -0.02301608,
         -0.04000423,  0.01110721],
        [-0.02572331, -0.00419756, -0.01576333, -0.00369692,
         -0.04649016, -0.02225201, -0.04041226, -0.02301608,
         -0.04000423,  0.01110721],
        [ 0.01212991,  0.01592976,  0.04301086,  0.01855068,
          0.00927285,  0.0392719 ,  0.04465056, -0.02398583,
          0.04329601,  0.04723711],
        [ 0.02037854, -0.01609875, -0.01944778,  0.04102537,
          0.03628058,  0.04142476, -0.02564578,  0.01296452,
         -0.00861623,  0.0484801 ],
        [-0.03125398,  0.03641218,  0.02229737, -0.0

In [28]:
embedded_docs[0]

array([   0,    0,    0,    0,   35, 6420, 7917, 3774], dtype=int32)

In [29]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


array([[[-0.02572331, -0.00419756, -0.01576333, -0.00369692,
         -0.04649016, -0.02225201, -0.04041226, -0.02301608,
         -0.04000423,  0.01110721],
        [-0.02572331, -0.00419756, -0.01576333, -0.00369692,
         -0.04649016, -0.02225201, -0.04041226, -0.02301608,
         -0.04000423,  0.01110721],
        [-0.02572331, -0.00419756, -0.01576333, -0.00369692,
         -0.04649016, -0.02225201, -0.04041226, -0.02301608,
         -0.04000423,  0.01110721],
        [-0.02572331, -0.00419756, -0.01576333, -0.00369692,
         -0.04649016, -0.02225201, -0.04041226, -0.02301608,
         -0.04000423,  0.01110721],
        [ 0.01212991,  0.01592976,  0.04301086,  0.01855068,
          0.00927285,  0.0392719 ,  0.04465056, -0.02398583,
          0.04329601,  0.04723711],
        [ 0.02037854, -0.01609875, -0.01944778,  0.04102537,
          0.03628058,  0.04142476, -0.02564578,  0.01296452,
         -0.00861623,  0.0484801 ],
        [-0.03125398,  0.03641218,  0.02229737, -0.0